meta_product_name: "GetOut"
meta_title: "GetOut - Places with music you love"
meta_description: "GetOut connects your Spotify listenings with bars that share the same tastes"
meta_image: "cover.png" # should exist in `app/assets/images/`
meta_url: "https://www.getout.bar"
