meta_product_name: "GetOut"
meta_title: "GetOut - Places with music you love"
meta_description: "GetOut connects your Spotify listenings with bars that share the same tastes"
meta_type: "website"
meta_image: "cover.png"
meta_url: "https://www.getout.bar"
